# Generated by Django 3.0.6 on 2020-05-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kennywoodapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attractions', to='kennywoodapi.ParkArea'),
        ),
    ]
